### ISSUE TITLE
Search-HawkTenantEXOAuditLog Forwarding Recipients

### ISSUE THREAD

**Issue by rerednawyerg** [T0pCyber/hawk#92]
**Describe the bug**
When running the Search-HawkTenantEXOAuditLog cmdlet I see the following line in the output:
## Investigate ## - Found 406 email addresses set to be forwarded mail
The forwarding_recipients.csv is created but it does not contain any content.
Simple_forwarding _changes.csv is created successfully and contains content.

**Steps to reproduce the behavior:**
Run the Search-HawkTenantEXOAuditLog cmdlet.

**Additional context**
Have tried running this multiple times with the same result.

**Comment by jonnybottles** [comment]
We wanted to let you know that this issue is being addressed as part of our ongoing efforts to update several scripts due to the deprecation of certain cmdlets by Microsoft. Specifically, this problem will be resolved through the updates outlined in the following tickets:

Ticket #146: [Bug: Update Get-HawkTenantRbacChanges.ps1 to Use Search-UnifiedAuditLog](https://github.com/T0pCyber/hawk/issues/146)
Ticket #147: [Bug: Update Search-HawkTenantEXOAuditLog.ps1 to Use Search-UnifiedAuditLog](https://github.com/T0pCyber/hawk/issues/147)
Ticket #148: [Update Get-HawkUserAdminAudit.ps1 to Use Search-UnifiedAuditLog](https://github.com/T0pCyber/hawk/issues/148)
Ticket #149: [Update Get-HawkUserMailboxAuditing.ps1 to Use Search-UnifiedAuditLog](https://github.com/T0pCyber/hawk/issues/149)
Ticket #150: [Update Get-HawkTenantEDiscoveryConfiguration.ps1 to Use Modern eDiscovery Cmdlets](https://github.com/T0pCyber/hawk/issues/150)
Ticket #147 is particularly relevant to the issue you've reported. By updating the Search-HawkTenantEXOAuditLog.ps1 script to use Search-UnifiedAuditLog and enhancing the parsing logic for the AuditData field, we expect the forwarding_recipients.csv file to be populated correctly with the forwarding addresses.
